server:
  port: 8080
spring:
  application:
    name: random-img
  r2dbc:
    url: r2dbc:mysql://localhost:3306/random_img
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.2.101
      port: 6379
random-img:
  basic-auth:
    username: username
    password: "{noop}passwd"
  s3:
    access-id: xxx
    access-token: xxx
    endpoint: http://localhost
    region: auto
    bucket-name: xxx
    cdn-url: http://localhost
  cloudreve:
    url: http://localhost
    username: xxx
    password: xxx
    image-account-uid: 0
    image-policy-id: 0
    s3-src: /
    cloudreve-dist: /
    recursive: true
  persistence-hosts:
    - localhost